version: '3.9'

services:
    frontend:
        image: thebarer/boards-frontend
        container_name: boards-frontend
        ports:
            - '80:5173'
        build:
            context: .
            dockerfile: Dockerfile

        networks:
            - boardsnetwork

networks:
    boardsnetwork:
        driver: bridge
