FROM node

WORKDIR /CLIENT

COPY package.json /CLIENT

RUN npm install

COPY . .

ARG VITE_APP_HOST
ARG VITE_API_ENDPOINT
ARG VITE_VK_CLIENT_ID
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_APP_DEV_MODE

ENV VITE_APP_HOST=$VITE_APP_HOST
ENV VITE_API_ENDPOINT=$VITE_API_ENDPOINT
ENV VITE_VK_CLIENT_ID=$VITE_VK_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_APP_DEV_MODE=$VITE_APP_DEV_MODE

RUN npm run build

EXPOSE 5173

CMD [ "npm", "run", "preview" ]