name: VPS-Update

on:
    workflow_run:
        workflows: ['Boards-build']
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: boards
        steps:
            - name: VPS restart docker
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  USERNAME: ${{ secrets.VPS_USER }}
                  PASSWORD: ${{ secrets.VPS_PASSWORD }}
                  KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd boards
                      docker compose stop
                      docker compose pull
                      docker compose up -d
