name: VPS update

on:
    workflow_run:
        workflows: ['build']
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: VPS restart docker
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  USERNAME: ${{ secrets.thebarer }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd boards
                      docker compose stop
                      docker compose pull
                      docker compose up
